#!/bin/sh
#############################################################################

export PKGNAME="wedderga"
export PKGVERSION="4.4.1"
export TOOLPATH="/Users/alexk/CVSREPS/GAPDEV/dev/DistributionUpdate/dist45"

cp ${TOOLPATH}/classifyfiles.py /Users/alexk/CVSREPS/GAPDEV/pkg/
cp ${TOOLPATH}/patternstextbinary.txt /Users/alexk/CVSREPS/GAPDEV/pkg/
cp patternscolor.txt /Users/alexk/CVSREPS/GAPDEV/pkg/

echo 'making a list of files to wrap'

cd /Users/alexk/CVSREPS/GAPDEV/pkg/

python ./classifyfiles.py $PKGNAME

echo '======================================================================'
echo 'list of text files to include'
cat listtextfiles.txt
echo '======================================================================'
echo 'list of binary files to include'
cat listbinaryfiles.txt
echo '======================================================================'
echo 'list of ignored files'
cat listignoredfiles.txt
echo '======================================================================'

cat listtextfiles.txt listbinaryfiles.txt > filestowrap.txt

rm -rf $PKGNAME-$PKGVERSION.tar.gz

tar -cvzf $PKGNAME-$PKGVERSION.tar.gz -T filestowrap.txt

rm listtextfiles.txt
rm listbinaryfiles.txt
rm listignoredfiles.txt
rm listtextfilesfortools.txt
rm listbinaryfilesfortools.txt
rm classifyfiles.py
rm patternscolor.txt
rm patternstextbinary.txt
rm filestowrap.txt

read -n 1 -p "Shall I copy $PKGNAME $PKGVERSION to its public website ? (y/n)> " ANSWER
echo

if [ $ANSWER = "y" ]; then
echo "Ok, I'll publish the data ..."
scp -p $PKGNAME-$PKGVERSION.tar.gz alexk@shell.cs.st-and.ac.uk:~/public_html/$PKGNAME/
cd $PKGNAME
scp -p PackageInfo.g alexk@shell.cs.st-and.ac.uk:~/public_html/$PKGNAME/
scp -p README alexk@shell.cs.st-and.ac.uk:~/public_html/$PKGNAME/ 
cd doc
scp -p * alexk@shell.cs.st-and.ac.uk:~/public_html/$PKGNAME/doc   
else
  echo "Don't publish, bye."
fi
