name: Wedderga
version: 4.9.1
date: 11/12/2017
description: |
    Wedderburn Decomposition of Group Algebras

authors:
    - name: Gurmeet Kaur Bakshi
      url: mailto:gkbakshi@pu.ac.in
    - name: Osnel Broche Cristo
      url: mailto:osnel@ufla.br
    - name: Allen Herman
      url: mailto:aherman@math.uregina.ca
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk
    - name: Sugandha Maheshwary
      url: mailto:sugandha@iisermohali.ac.in
    - name: Gabriela Olteanu
      url: http://math.ubbcluj.ro/~olteanu
    - name: Aurora Olivieri
      url: mailto:olivieri@usb.ve
    - name: Angel del Rio
      url: http://www.um.es/adelrio
    - name: Inneke Van Gelder
      url: http://homepages.vub.ac.be/~ivgelder

maintainers:
    - name: Gurmeet Kaur Bakshi
      url: mailto:gkbakshi@pu.ac.in
    - name: Osnel Broche Cristo
      url: mailto:osnel@ufla.br
    - name: Allen Herman
      url: mailto:aherman@math.uregina.ca
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk
    - name: Sugandha Maheshwary
      url: mailto:sugandha@iisermohali.ac.in
    - name: Gabriela Olteanu
      url: http://math.ubbcluj.ro/~olteanu
    - name: Aurora Olivieri
      url: mailto:olivieri@usb.ve
    - name: Angel del Rio
      url: http://www.um.es/adelrio
    - name: Inneke Van Gelder
      url: http://homepages.vub.ac.be/~ivgelder

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "laguna"
      version: ">= 3.4"
      url: "https://gap-packages.github.io/laguna"
    - name: "GUAVA"
      version: ">= 3.12"
      url: "http://osj1961.github.io/guava/"

www: https://gap-packages.github.io/wedderga
readme: README.md
packageinfo: https://gap-packages.github.io/wedderga/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/wedderga/releases/download/v4.9.1/wedderga-4.9.1.tar.gz

abstract: |
    <span class="pkgname">Wedderga</span> is the package to compute the simple components of the Wedderburn decomposition of semisimple group algebras of finite groups over finite fields and over subfields of finite cyclotomic extensions of the rationals. It also contains functions that produce the primitive central idempotents of semisimple group algebras and functions for computing Schur indices. Other functions of <span class="pkgname">Wedderga</span> allow one to construct crossed products over a group with coefficients in an associative ring with identity and the multiplication determined by a given action and twisting.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
