name: Wedderga
version: "4.11.0"
license: "GPL-2.0-or-later"
date: 2025-06-16
description: |
    Wedderburn Decomposition of Group Algebras

authors:
    - name: Gurmeet Kaur Bakshi
      url: mailto:gkbakshi@pu.ac.in
    - name: Osnel Broche Cristo
      url: mailto:osnel@ufla.br
    - name: Allen Herman
      url: mailto:aherman@math.uregina.ca
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Sugandha Maheshwary
      url: mailto:msugandha@ma.iitr.ac.in
    - name: Gabriela Olteanu
      url: http://math.ubbcluj.ro/~olteanu
    - name: Aurora Olivieri
      url: mailto:olivieri@usb.ve
    - name: Angel del Rio
      url: http://www.um.es/adelrio
    - name: Inneke Van Gelder
      url: http://homepages.vub.ac.be/~ivgelder

maintainers:
    - name: Gurmeet Kaur Bakshi
      url: mailto:gkbakshi@pu.ac.in
    - name: Osnel Broche Cristo
      url: mailto:osnel@ufla.br
    - name: Allen Herman
      url: mailto:aherman@math.uregina.ca
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Sugandha Maheshwary
      url: mailto:msugandha@ma.iitr.ac.in
    - name: Gabriela Olteanu
      url: http://math.ubbcluj.ro/~olteanu
    - name: Aurora Olivieri
      url: mailto:olivieri@usb.ve
    - name: Angel del Rio
      url: http://www.um.es/adelrio
    - name: Inneke Van Gelder
      url: http://homepages.vub.ac.be/~ivgelder

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "laguna"
      version: ">= 3.4"
      url: "https://gap-packages.github.io/laguna"
    - name: "GUAVA"
      version: ">= 3.12"
      url: "https://gap-packages.github.io/guava"

www: https://gap-packages.github.io/wedderga
readme: README.md
packageinfo: https://gap-packages.github.io/wedderga/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/wedderga/releases/download/v4.11.0/wedderga-4.11.0.tar.gz

abstract: |
    <span class="pkgname">Wedderga</span> is the package to compute the simple components of the Wedderburn decomposition of semisimple group algebras of finite groups over finite fields and over subfields of finite cyclotomic extensions of the rationals. It also contains functions that produce the primitive central idempotents of semisimple group algebras and functions for computing Schur indices. Other functions of <span class="pkgname">Wedderga</span> allow one to construct crossed products over a group with coefficients in an associative ring with identity and the multiplication determined by a given action and twisting.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Wedderburn decomposition, simple components, central idempotents, group algebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BCHKMOORG25</span>]   <b class='BibAuthor'>Bakshi, G. K., Broche Cristo, O., Herman, A., Konovalov, O., Maheshwary, S., Olteanu, G., Olivieri, A., del Rio, A. and Van Gelder, I.</b>,
     <i class='BibTitle'>Wedderga, Wedderburn Decomposition of Group Algebras,
             Version 4.11.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/wedderga">https://gap-packages.github.io/wedderga</a></span>.
    </p>
    

bibtex: |
    @misc{ Wedderga,
      author =           {Bakshi, G. K. and Broche Cristo, O. and Herman, A. and
                          Konovalov,  O.  and Maheshwary, S. and Olteanu, G. and
                          Olivieri, A. and del Rio, A. and Van Gelder, I.},
      title =            {{Wedderga},   {Wedderburn   Decomposition   of   Group
                          Algebras}, {V}ersion 4.11.0},
      month =            {Jun},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/wedderga}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{wedderga}}},
      keywords =         {Wedderburn  decomposition;  simple components; central
                          idempotents; group algebras},
      printedkey =       {BCHKMOORG25}
    }

